/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.3
 * Generated at: 2016-06-27 07:35:08 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class ex15_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("jar:file:/D:/NTAj53/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/JSTLApp-XML/WEB-INF/lib/standard.jar!/META-INF/x.tld", Long.valueOf(1098691290000L));
    _jspx_dependants.put("/WEB-INF/lib/standard.jar", Long.valueOf(1462766950085L));
    _jspx_dependants.put("jar:file:/D:/NTAj53/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/JSTLApp-XML/WEB-INF/lib/standard.jar!/META-INF/c.tld", Long.valueOf(1098691290000L));
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fimport_0026_005fvar_005furl_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fx_005fparse_0026_005fxml_005fvar_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fx_005fforEach_0026_005fvar_005fselect;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fx_005fout_0026_005fselect_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fx_005fif_0026_005fselect;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fimport_0026_005fvar_005furl_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fx_005fparse_0026_005fxml_005fvar_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fx_005fforEach_0026_005fvar_005fselect = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fx_005fout_0026_005fselect_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fx_005fif_0026_005fselect = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fimport_0026_005fvar_005furl_005fnobody.release();
    _005fjspx_005ftagPool_005fx_005fparse_0026_005fxml_005fvar_005fnobody.release();
    _005fjspx_005ftagPool_005fx_005fforEach_0026_005fvar_005fselect.release();
    _005fjspx_005ftagPool_005fx_005fout_0026_005fselect_005fnobody.release();
    _005fjspx_005ftagPool_005fx_005fif_0026_005fselect.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- loads file -->\r\n");
      if (_jspx_meth_c_005fimport_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("<!-- parses the file -->\r\n");
      if (_jspx_meth_x_005fparse_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("<br>\r\n");
      out.write("\r\n");
      out.write("printing all item deails <br>\r\n");
      if (_jspx_meth_x_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("<br>\r\n");
      out.write("\r\n");
      out.write("printing items whose price >= 500 <br>\r\n");
      if (_jspx_meth_x_005fforEach_005f1(_jspx_page_context))
        return;
      out.write('\r');
      out.write('\n');
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fimport_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:import
    org.apache.taglibs.standard.tag.rt.core.ImportTag _jspx_th_c_005fimport_005f0 = (org.apache.taglibs.standard.tag.rt.core.ImportTag) _005fjspx_005ftagPool_005fc_005fimport_0026_005fvar_005furl_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.ImportTag.class);
    _jspx_th_c_005fimport_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fimport_005f0.setParent(null);
    // /ex15.jsp(5,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fimport_005f0.setVar("file");
    // /ex15.jsp(5,0) name = url type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fimport_005f0.setUrl("orders.xml");
    int[] _jspx_push_body_count_c_005fimport_005f0 = new int[] { 0 };
    try {
      int _jspx_eval_c_005fimport_005f0 = _jspx_th_c_005fimport_005f0.doStartTag();
      if (_jspx_th_c_005fimport_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } catch (java.lang.Throwable _jspx_exception) {
      while (_jspx_push_body_count_c_005fimport_005f0[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_c_005fimport_005f0.doCatch(_jspx_exception);
    } finally {
      _jspx_th_c_005fimport_005f0.doFinally();
      _005fjspx_005ftagPool_005fc_005fimport_0026_005fvar_005furl_005fnobody.reuse(_jspx_th_c_005fimport_005f0);
    }
    return false;
  }

  private boolean _jspx_meth_x_005fparse_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  x:parse
    org.apache.taglibs.standard.tag.rt.xml.ParseTag _jspx_th_x_005fparse_005f0 = (org.apache.taglibs.standard.tag.rt.xml.ParseTag) _005fjspx_005ftagPool_005fx_005fparse_0026_005fxml_005fvar_005fnobody.get(org.apache.taglibs.standard.tag.rt.xml.ParseTag.class);
    _jspx_th_x_005fparse_005f0.setPageContext(_jspx_page_context);
    _jspx_th_x_005fparse_005f0.setParent(null);
    // /ex15.jsp(7,0) name = xml type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_x_005fparse_005f0.setXml((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${file}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
    // /ex15.jsp(7,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_x_005fparse_005f0.setVar("doc");
    int _jspx_eval_x_005fparse_005f0 = _jspx_th_x_005fparse_005f0.doStartTag();
    if (_jspx_th_x_005fparse_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fx_005fparse_0026_005fxml_005fvar_005fnobody.reuse(_jspx_th_x_005fparse_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fx_005fparse_0026_005fxml_005fvar_005fnobody.reuse(_jspx_th_x_005fparse_005f0);
    return false;
  }

  private boolean _jspx_meth_x_005fforEach_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  x:forEach
    org.apache.taglibs.standard.tag.common.xml.ForEachTag _jspx_th_x_005fforEach_005f0 = (org.apache.taglibs.standard.tag.common.xml.ForEachTag) _005fjspx_005ftagPool_005fx_005fforEach_0026_005fvar_005fselect.get(org.apache.taglibs.standard.tag.common.xml.ForEachTag.class);
    _jspx_th_x_005fforEach_005f0.setPageContext(_jspx_page_context);
    _jspx_th_x_005fforEach_005f0.setParent(null);
    // /ex15.jsp(11,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_x_005fforEach_005f0.setVar("ord");
    // /ex15.jsp(11,0) name = select type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_x_005fforEach_005f0.setSelect("$doc/orders/order");
    int[] _jspx_push_body_count_x_005fforEach_005f0 = new int[] { 0 };
    try {
      int _jspx_eval_x_005fforEach_005f0 = _jspx_th_x_005fforEach_005f0.doStartTag();
      if (_jspx_eval_x_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("    Name: ");
          if (_jspx_meth_x_005fout_005f0(_jspx_th_x_005fforEach_005f0, _jspx_page_context, _jspx_push_body_count_x_005fforEach_005f0))
            return true;
          out.write("<br>\r\n");
          out.write("    price: ");
          if (_jspx_meth_x_005fout_005f1(_jspx_th_x_005fforEach_005f0, _jspx_page_context, _jspx_push_body_count_x_005fforEach_005f0))
            return true;
          out.write("<br>\r\n");
          int evalDoAfterBody = _jspx_th_x_005fforEach_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_x_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } catch (java.lang.Throwable _jspx_exception) {
      while (_jspx_push_body_count_x_005fforEach_005f0[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_x_005fforEach_005f0.doCatch(_jspx_exception);
    } finally {
      _jspx_th_x_005fforEach_005f0.doFinally();
      _005fjspx_005ftagPool_005fx_005fforEach_0026_005fvar_005fselect.reuse(_jspx_th_x_005fforEach_005f0);
    }
    return false;
  }

  private boolean _jspx_meth_x_005fout_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_x_005fforEach_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_x_005fforEach_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  x:out
    org.apache.taglibs.standard.tag.rt.xml.ExprTag _jspx_th_x_005fout_005f0 = (org.apache.taglibs.standard.tag.rt.xml.ExprTag) _005fjspx_005ftagPool_005fx_005fout_0026_005fselect_005fnobody.get(org.apache.taglibs.standard.tag.rt.xml.ExprTag.class);
    _jspx_th_x_005fout_005f0.setPageContext(_jspx_page_context);
    _jspx_th_x_005fout_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_x_005fforEach_005f0);
    // /ex15.jsp(12,10) name = select type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_x_005fout_005f0.setSelect("$ord/item");
    int _jspx_eval_x_005fout_005f0 = _jspx_th_x_005fout_005f0.doStartTag();
    if (_jspx_th_x_005fout_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fx_005fout_0026_005fselect_005fnobody.reuse(_jspx_th_x_005fout_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fx_005fout_0026_005fselect_005fnobody.reuse(_jspx_th_x_005fout_005f0);
    return false;
  }

  private boolean _jspx_meth_x_005fout_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_x_005fforEach_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_x_005fforEach_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  x:out
    org.apache.taglibs.standard.tag.rt.xml.ExprTag _jspx_th_x_005fout_005f1 = (org.apache.taglibs.standard.tag.rt.xml.ExprTag) _005fjspx_005ftagPool_005fx_005fout_0026_005fselect_005fnobody.get(org.apache.taglibs.standard.tag.rt.xml.ExprTag.class);
    _jspx_th_x_005fout_005f1.setPageContext(_jspx_page_context);
    _jspx_th_x_005fout_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_x_005fforEach_005f0);
    // /ex15.jsp(13,11) name = select type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_x_005fout_005f1.setSelect("$ord/price");
    int _jspx_eval_x_005fout_005f1 = _jspx_th_x_005fout_005f1.doStartTag();
    if (_jspx_th_x_005fout_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fx_005fout_0026_005fselect_005fnobody.reuse(_jspx_th_x_005fout_005f1);
      return true;
    }
    _005fjspx_005ftagPool_005fx_005fout_0026_005fselect_005fnobody.reuse(_jspx_th_x_005fout_005f1);
    return false;
  }

  private boolean _jspx_meth_x_005fforEach_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  x:forEach
    org.apache.taglibs.standard.tag.common.xml.ForEachTag _jspx_th_x_005fforEach_005f1 = (org.apache.taglibs.standard.tag.common.xml.ForEachTag) _005fjspx_005ftagPool_005fx_005fforEach_0026_005fvar_005fselect.get(org.apache.taglibs.standard.tag.common.xml.ForEachTag.class);
    _jspx_th_x_005fforEach_005f1.setPageContext(_jspx_page_context);
    _jspx_th_x_005fforEach_005f1.setParent(null);
    // /ex15.jsp(18,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_x_005fforEach_005f1.setVar("ord");
    // /ex15.jsp(18,0) name = select type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_x_005fforEach_005f1.setSelect("$doc/orders/order");
    int[] _jspx_push_body_count_x_005fforEach_005f1 = new int[] { 0 };
    try {
      int _jspx_eval_x_005fforEach_005f1 = _jspx_th_x_005fforEach_005f1.doStartTag();
      if (_jspx_eval_x_005fforEach_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("  ");
          if (_jspx_meth_x_005fif_005f0(_jspx_th_x_005fforEach_005f1, _jspx_page_context, _jspx_push_body_count_x_005fforEach_005f1))
            return true;
          out.write('\r');
          out.write('\n');
          int evalDoAfterBody = _jspx_th_x_005fforEach_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_x_005fforEach_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } catch (java.lang.Throwable _jspx_exception) {
      while (_jspx_push_body_count_x_005fforEach_005f1[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_x_005fforEach_005f1.doCatch(_jspx_exception);
    } finally {
      _jspx_th_x_005fforEach_005f1.doFinally();
      _005fjspx_005ftagPool_005fx_005fforEach_0026_005fvar_005fselect.reuse(_jspx_th_x_005fforEach_005f1);
    }
    return false;
  }

  private boolean _jspx_meth_x_005fif_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_x_005fforEach_005f1, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_x_005fforEach_005f1)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  x:if
    org.apache.taglibs.standard.tag.common.xml.IfTag _jspx_th_x_005fif_005f0 = (org.apache.taglibs.standard.tag.common.xml.IfTag) _005fjspx_005ftagPool_005fx_005fif_0026_005fselect.get(org.apache.taglibs.standard.tag.common.xml.IfTag.class);
    _jspx_th_x_005fif_005f0.setPageContext(_jspx_page_context);
    _jspx_th_x_005fif_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_x_005fforEach_005f1);
    // /ex15.jsp(19,2) name = select type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_x_005fif_005f0.setSelect("$ord/price>=500");
    int _jspx_eval_x_005fif_005f0 = _jspx_th_x_005fif_005f0.doStartTag();
    if (_jspx_eval_x_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\r\n");
        out.write("    Name: ");
        if (_jspx_meth_x_005fout_005f2(_jspx_th_x_005fif_005f0, _jspx_page_context, _jspx_push_body_count_x_005fforEach_005f1))
          return true;
        out.write("<br>\r\n");
        out.write("    price: ");
        if (_jspx_meth_x_005fout_005f3(_jspx_th_x_005fif_005f0, _jspx_page_context, _jspx_push_body_count_x_005fforEach_005f1))
          return true;
        out.write("<br>\r\n");
        out.write("  ");
        int evalDoAfterBody = _jspx_th_x_005fif_005f0.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_x_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fx_005fif_0026_005fselect.reuse(_jspx_th_x_005fif_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fx_005fif_0026_005fselect.reuse(_jspx_th_x_005fif_005f0);
    return false;
  }

  private boolean _jspx_meth_x_005fout_005f2(javax.servlet.jsp.tagext.JspTag _jspx_th_x_005fif_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_x_005fforEach_005f1)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  x:out
    org.apache.taglibs.standard.tag.rt.xml.ExprTag _jspx_th_x_005fout_005f2 = (org.apache.taglibs.standard.tag.rt.xml.ExprTag) _005fjspx_005ftagPool_005fx_005fout_0026_005fselect_005fnobody.get(org.apache.taglibs.standard.tag.rt.xml.ExprTag.class);
    _jspx_th_x_005fout_005f2.setPageContext(_jspx_page_context);
    _jspx_th_x_005fout_005f2.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_x_005fif_005f0);
    // /ex15.jsp(20,10) name = select type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_x_005fout_005f2.setSelect("$ord/item");
    int _jspx_eval_x_005fout_005f2 = _jspx_th_x_005fout_005f2.doStartTag();
    if (_jspx_th_x_005fout_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fx_005fout_0026_005fselect_005fnobody.reuse(_jspx_th_x_005fout_005f2);
      return true;
    }
    _005fjspx_005ftagPool_005fx_005fout_0026_005fselect_005fnobody.reuse(_jspx_th_x_005fout_005f2);
    return false;
  }

  private boolean _jspx_meth_x_005fout_005f3(javax.servlet.jsp.tagext.JspTag _jspx_th_x_005fif_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_x_005fforEach_005f1)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  x:out
    org.apache.taglibs.standard.tag.rt.xml.ExprTag _jspx_th_x_005fout_005f3 = (org.apache.taglibs.standard.tag.rt.xml.ExprTag) _005fjspx_005ftagPool_005fx_005fout_0026_005fselect_005fnobody.get(org.apache.taglibs.standard.tag.rt.xml.ExprTag.class);
    _jspx_th_x_005fout_005f3.setPageContext(_jspx_page_context);
    _jspx_th_x_005fout_005f3.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_x_005fif_005f0);
    // /ex15.jsp(21,11) name = select type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_x_005fout_005f3.setSelect("$ord/price");
    int _jspx_eval_x_005fout_005f3 = _jspx_th_x_005fout_005f3.doStartTag();
    if (_jspx_th_x_005fout_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fx_005fout_0026_005fselect_005fnobody.reuse(_jspx_th_x_005fout_005f3);
      return true;
    }
    _005fjspx_005ftagPool_005fx_005fout_0026_005fselect_005fnobody.reuse(_jspx_th_x_005fout_005f3);
    return false;
  }
}
